This is makeindex, version 2.18 [MiKTeX 26.5].
Scanning style file ./Skript_Passwortsicherheit.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Skript_Passwortsicherheit.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file Skript_Passwortsicherheit.acr....done (6 lines written, 0 warnings).
Output written in Skript_Passwortsicherheit.acr.
Transcript written in Skript_Passwortsicherheit.alg.
